# Generated by Django 3.2.5 on 2021-07-31 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('emp', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fechanac', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('genero', models.CharField(blank=True, max_length=5, null=True)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('cel', models.CharField(blank=True, max_length=10, null=True)),
                ('fechaing', models.DateField()),
                ('depto', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
    ]
