# Generated by Django 3.2.5 on 2021-07-31 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionEmpleados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='emp',
            field=models.IntegerField(null=True, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='depto',
            field=models.IntegerField(null=True, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fechaing',
            field=models.DateField(verbose_name='Fecha de Ingreso'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fechanac',
            field=models.DateField(verbose_name='Fecha de Nacimiento'),
        ),
    ]
