# Generated by Django 3.2.5 on 2021-08-01 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionEmpleados', '0002_auto_20210731_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='emp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionEmpleados.empresa'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='depto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionEmpleados.departamento'),
        ),
    ]
